import type {Metadata} from "next";
import "./globals.css";
import localFont from 'next/font/local'
import {ReactNode} from "react";
import MainLayout from "@/public/layouts/mainLayout";
import ShoppingCartContextProvider from "@/context/shoppingCartContext";

const Tanha = localFont({src: '../public/assets/fonts/Tanha.woff2'});

export const metadata: Metadata = {
    title: "Online Shop",
    description: "Generated by create next app",
};

const RootLayout = ({children,}: Readonly<{ children: ReactNode; }>) => {
    return (
        <html lang="fa-IR" dir="rtl">
        <body className={`${Tanha.className}`}>
        <ShoppingCartContextProvider>
            <MainLayout>
                {children}
            </MainLayout>
        </ShoppingCartContextProvider>
        </body>
        </html>
    );
}

export default RootLayout;
